### ISSUE TITLE
Output Eslint Results (Tue. Nov. 19)

### ISSUE THREAD

**Issue by danielanatolie** [danielanatolie/devis#3]
**Challege**
Currently, running `./node_modules/.bin/eslint src` runs the eslint checker on the src folder and prints the results to terminal.
Instead, make the eslint print useful results to a json object that we can use.

**Example**
1. ./node_modules/.bin/eslint src
2. eslint results stored in an object called eslintJsonObj

**Comment by pedraumks** [comment]
Running `./node_modules/.bin/eslint test --format json > eslintJsonObj.json` stores the ESLint results to to the object, eslintJsonObj.

**Comment by danielanatolie** [comment]
Can you post what the object looks like here?

**Comment by pedraumks** [comment]
`[{"filePath":"/Users/pedraumsafarzadeh/Downloads/devis/test/project1/files/App.js","messages":[{"ruleId":"@typescript-eslint/no-unused-vars","severity":1,"message":"'React' is defined but never used.","line":1,"column":8,"nodeType":"Identifier","endLine":1,"endColumn":13},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":5,"column":1,"nodeType":"FunctionDeclaration","messageId":"missingReturnType","endLine":5,"endColumn":15}],"errorCount":0,"warningCount":2,"fixableErrorCount":0,"fixableWarningCount":0,"source":"import React from 'react';\nimport logo from './logo.svg';\nimport './App.css';\n\nfunction App() {\n  return (\n    <div className=\"App\">\n      <header className=\"App-header\">\n        <img src={logo} className=\"App-logo\" alt=\"logo\" />\n        <p>\n          Edit <code>src/App.js</code> and save to reload.\n        </p>\n        <a\n          className=\"App-link\"\n          href=\"https://reactjs.org\"\n          target=\"_blank\"\n          rel=\"noopener noreferrer\"\n        >\n          Learn React\n        </a>\n      </header>\n    </div>\n  );\n}\n\nexport default App;\n"},{"filePath":"/Users/pedraumsafarzadeh/Downloads/devis/test/project1/files/App.test.js","messages":[{"ruleId":"@typescript-eslint/no-unused-vars","severity":1,"message":"'React' is defined but never used.","line":1,"column":8,"nodeType":"Identifier","endLine":1,"endColumn":13},{"ruleId":"@typescript-eslint/no-unused-vars","severity":1,"message":"'App' is defined but never used.","line":3,"column":8,"nodeType":"Identifier","endLine":3,"endColumn":11}],"errorCount":0,"warningCount":2,"fixableErrorCount":0,"fixableWarningCount":0,"source":"import React from 'react';\nimport ReactDOM from 'react-dom';\nimport App from './App';\n\nit('renders without crashing', () => {\n  const div = document.createElement('div');\n  ReactDOM.render(<App />, div);\n  ReactDOM.unmountComponentAtNode(div);\n});\n"},{"filePath":"/Users/pedraumsafarzadeh/Downloads/devis/test/project1/files/index.js","messages":[{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":1,"column":18,"nodeType":"FunctionExpression","messageId":"missingReturnType","endLine":1,"endColumn":46}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0,"source":"module.exports = async function(context, req) {\n  context.log(\"JavaScript HTTP trigger function processed a request.\");\n\n  if (req.query.name || (req.body && req.body.name)) {\n    context.res = {\n      // status: 200, /* Defaults to 200 */\n      body: \"Hello \" + (req.query.name || req.body.name)\n    };\n  } else {\n    context.res = {\n      status: 400,\n      body: \"Please pass a name on the query string or in the request body\"\n    };\n  }\n};\n"},{"filePath":"/Users/pedraumsafarzadeh/Downloads/devis/test/project1/files/serviceWorker.js","messages":[{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":23,"column":8,"nodeType":"FunctionDeclaration","messageId":"missingReturnType","endLine":23,"endColumn":33},{"ruleId":"@typescript-eslint/no-use-before-define","severity":2,"message":"'checkValidServiceWorker' was used before it was defined.","line":39,"column":9,"nodeType":"Identifier","messageId":"noUseBeforeDefine","endLine":39,"endColumn":32},{"ruleId":"@typescript-eslint/no-use-before-define","severity":2,"message":"'registerValidSW' was used before it was defined.","line":51,"column":9,"nodeType":"Identifier","messageId":"noUseBeforeDefine","endLine":51,"endColumn":24},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":57,"column":1,"nodeType":"FunctionDeclaration","messageId":"missingReturnType","endLine":57,"endColumn":40},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":61,"column":36,"nodeType":"ArrowFunctionExpression","messageId":"missingReturnType","endLine":61,"endColumn":41},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":66,"column":42,"nodeType":"ArrowFunctionExpression","messageId":"missingReturnType","endLine":66,"endColumn":47},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":101,"column":1,"nodeType":"FunctionDeclaration","messageId":"missingReturnType","endLine":101,"endColumn":48},{"ruleId":"@typescript-eslint/explicit-function-return-type","severity":1,"message":"Missing return type on function.","line":129,"column":8,"nodeType":"FunctionDeclaration","messageId":"missingReturnType","endLine":129,"endColumn":29}],"errorCount":2,"warningCount":6,"fixableErrorCount":0,"fixableWarningCount":0,"source":"// This optional code is used to register a service worker.\n// register() is not called by default.\n\n// This lets the app load faster on subsequent visits in production, and gives\n// it offline capabilities. However, it also means that developers (and users)\n// will only see deployed updates on subsequent visits to a page, after all the\n// existing tabs open on the page have been closed, since previously cached\n// resources are updated in the background.\n\n// To learn more about the benefits of this model and instructions on how to\n// opt-in, read https://bit.ly/CRA-PWA\n\nconst isLocalhost = Boolean(\n  window.location.hostname === 'localhost' ||\n    // [::1] is the IPv6 localhost address.\n    window.location.hostname === '[::1]' ||\n    // 127.0.0.1/8 is considered localhost for IPv4.\n    window.location.hostname.match(\n      /^127(?:\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/\n    )\n);\n\nexport function register(config) {\n  if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {\n    // The URL constructor is available in all browsers that support SW.\n    const publicUrl = new URL(process.env.PUBLIC_URL, window.location.href);\n    if (publicUrl.origin !== window.location.origin) {\n      // Our service worker won't work if PUBLIC_URL is on a different origin\n      // from what our page is served on. This might happen if a CDN is used to\n      // serve assets; see https://github.com/facebook/create-react-app/issues/2374\n      return;\n    }\n\n    window.addEventListener('load', () => {\n      const swUrl = `${process.env.PUBLIC_URL}/service-worker.js`;\n\n      if (isLocalhost) {\n        // This is running on localhost. Let's check if a service worker still exists or not.\n        checkValidServiceWorker(swUrl, config);\n\n        // Add some additional logging to localhost, pointing developers to the\n        // service worker/PWA documentation.\n        navigator.serviceWorker.ready.then(() => {\n          console.log(\n            'This web app is being served cache-first by a service ' +\n              'worker. To learn more, visit https://bit.ly/CRA-PWA'\n          );\n        });\n      } else {\n        // Is not localhost. Just register service worker\n        registerValidSW(swUrl, config);\n      }\n    });\n  }\n}\n\nfunction registerValidSW(swUrl, config) {\n  navigator.serviceWorker\n    .register(swUrl)\n    .then(registration => {\n      registration.onupdatefound = () => {\n        const installingWorker = registration.installing;\n        if (installingWorker == null) {\n          return;\n        }\n        installingWorker.onstatechange = () => {\n          if (installingWorker.state === 'installed') {\n            if (navigator.serviceWorker.controller) {\n              // At this point, the updated precached content has been fetched,\n              // but the previous service worker will still serve the older\n              // content until all client tabs are closed.\n              console.log(\n                'New content is available and will be used when all ' +\n                  'tabs for this page are closed. See https://bit.ly/CRA-PWA.'\n              );\n\n              // Execute callback\n              if (config && config.onUpdate) {\n                config.onUpdate(registration);\n              }\n            } else {\n              // At this point, everything has been precached.\n              // It's the perfect time to display a\n              // \"Content is cached for offline use.\" message.\n              console.log('Content is cached for offline use.');\n\n              // Execute callback\n              if (config && config.onSuccess) {\n                config.onSuccess(registration);\n              }\n            }\n          }\n        };\n      };\n    })\n    .catch(error => {\n      console.error('Error during service worker registration:', error);\n    });\n}\n\nfunction checkValidServiceWorker(swUrl, config) {\n  // Check if the service worker can be found. If it can't reload the page.\n  fetch(swUrl)\n    .then(response => {\n      // Ensure service worker exists, and that we really are getting a JS file.\n      const contentType = response.headers.get('content-type');\n      if (\n        response.status === 404 ||\n        (contentType != null && contentType.indexOf('javascript') === -1)\n      ) {\n        // No service worker found. Probably a different app. Reload the page.\n        navigator.serviceWorker.ready.then(registration => {\n          registration.unregister().then(() => {\n            window.location.reload();\n          });\n        });\n      } else {\n        // Service worker found. Proceed as normal.\n        registerValidSW(swUrl, config);\n      }\n    })\n    .catch(() => {\n      console.log(\n        'No internet connection found. App is running in offline mode.'\n      );\n    });\n}\n\nexport function unregister() {\n  if ('serviceWorker' in navigator) {\n    navigator.serviceWorker.ready.then(registration => {\n      registration.unregister();\n    });\n  }\n}\n"}]
`

**Comment by pedraumks** [comment]
Looks very very ugly haha

**Comment by danielanatolie** [comment]
Naw it looks find if you view it through a json viewer: 
![Screenshot 2019-11-14 at 1 05 20 PM](https://user-images.githubusercontent.com/19753556/68896037-75ad8080-06df-11ea-9fab-804038130949.png)

We just need more code data aside from errorCount and warningCount, try playing around with the eslintrc file

**Comment by danielanatolie** [comment]
https://github.com/danielanatolie/devis/pull/18
